# Generated by Django 4.1 on 2024-11-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="newsreport/media", verbose_name="文件"),
                ),
                (
                    "file_name",
                    models.CharField(
                        default="data.csv", max_length=50, verbose_name="文件名称"
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                (
                    "host_ip",
                    models.CharField(
                        default="127.0.0.1", max_length=50, verbose_name="主机IP"
                    ),
                ),
                ("comment", models.CharField(max_length=100, verbose_name="备注说明")),
                ("isanalyse", models.BooleanField(default="0", verbose_name="是否分析")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("ans_text", models.CharField(default=0, max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CAS_Registry_Number_CAS", models.CharField(max_length=200)),
                (
                    "Normal_boiling_temperature_Tb",
                    models.CharField(default=0, max_length=200),
                ),
                (
                    "Normal_melting_temperature_Tm",
                    models.CharField(default=0, max_length=200),
                ),
                ("Density_dens", models.CharField(default=0, max_length=200)),
                (
                    "Thermal_conductivity_Tcond",
                    models.CharField(default=0, max_length=200),
                ),
                (
                    "Electrical_conductivity_econd",
                    models.CharField(default=0, max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test_urser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CAS_Registry_Number_CAS", models.CharField(max_length=200)),
                (
                    "Normal_boiling_temperature_Tb",
                    models.CharField(default=0, max_length=200),
                ),
                (
                    "Normal_melting_temperature_Tm",
                    models.CharField(default=0, max_length=200),
                ),
                ("Density_dens", models.CharField(default=0, max_length=200)),
                (
                    "Thermal_conductivity_Tcond",
                    models.CharField(default=0, max_length=200),
                ),
                (
                    "Electrical_conductivity_econd",
                    models.CharField(default=0, max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="similarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_title", models.CharField(default=0, max_length=200)),
                ("similarity_data", models.CharField(default=0, max_length=200)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Chemai_data.test",
                    ),
                ),
            ],
        ),
    ]
