# Generated by Django 4.1 on 2024-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="Chemai_data/media", verbose_name="文件"),
                ),
                (
                    "file_name",
                    models.CharField(
                        default="data.csv", max_length=50, verbose_name="文件名称"
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                (
                    "host_ip",
                    models.CharField(
                        default="127.0.0.1", max_length=50, verbose_name="主机IP"
                    ),
                ),
                ("comment", models.CharField(max_length=100, verbose_name="备注说明")),
                ("isanalyse", models.BooleanField(default="0", verbose_name="是否分析")),
            ],
        ),
        migrations.DeleteModel(name="Logfile",),
    ]
