# Generated by Django 4.1 on 2024-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0002_files_delete_logfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "数据库信息", "verbose_name_plural": "数据库信息"},
        ),
        migrations.AlterField(
            model_name="similarity",
            name="similarity_data",
            field=models.CharField(default=0, max_length=200, verbose_name="相似性比例"),
        ),
        migrations.AlterField(
            model_name="similarity",
            name="similarity_title",
            field=models.CharField(default=0, max_length=200, verbose_name="相似性名字"),
        ),
        migrations.AlterField(
            model_name="test",
            name="CAS_Registry_Number_CAS",
            field=models.CharField(max_length=200, verbose_name="关键字"),
        ),
        migrations.AlterField(
            model_name="test",
            name="Density_dens",
            field=models.CharField(default=0, max_length=200, verbose_name="密度"),
        ),
        migrations.AlterField(
            model_name="test",
            name="Normal_boiling_temperature_Tb",
            field=models.CharField(default=0, max_length=200, verbose_name="常沸点温度"),
        ),
        migrations.AlterField(
            model_name="test",
            name="Normal_melting_temperature_Tm",
            field=models.CharField(default=0, max_length=200, verbose_name="正常熔化温度"),
        ),
    ]
