# Generated by Django 4.1 on 2024-11-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Chemai_data",
            "0003_alter_test_options_alter_similarity_similarity_data_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="Test", new_name="Chem_mol",),
        migrations.RenameModel(old_name="Files", new_name="Fil",),
        migrations.RenameModel(old_name="Question", new_name="Fun",),
        migrations.RenameModel(old_name="similarity", new_name="Sim",),
        migrations.RenameModel(old_name="Test_urser", new_name="Test_Chem_mol",),
    ]
