# Generated by Django 4.1 on 2024-12-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0004_rename_test_chem_mol_rename_files_fil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chem_mol",
            name="Molecular_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子名称"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="SMILES",
            field=models.CharField(default=0, max_length=200, verbose_name="SMILES表示"),
        ),
    ]
