# Generated by Django 4.1 on 2024-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0005_chem_mol_molecular_formla_chem_mol_smiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="chem_mol",
            name="ImageField",
            field=models.ImageField(
                default="/default.jpg", upload_to="Chemai_data/media", verbose_name="结构"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Inchikey",
            field=models.CharField(default=0, max_length=200, verbose_name="关键字"),
        ),
        migrations.AlterField(
            model_name="chem_mol",
            name="CAS_Registry_Number_CAS",
            field=models.CharField(max_length=200, verbose_name="CAS"),
        ),
    ]
