# Generated by Django 4.1 on 2024-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0006_chem_mol_imagefield_chem_mol_inchikey_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="chem_mol", name="ImageField",),
        migrations.AddField(
            model_name="chem_mol",
            name="photo",
            field=models.CharField(default=0, max_length=200, verbose_name="结构"),
        ),
    ]
