# Generated by Django 4.1 on 2024-12-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0007_remove_chem_mol_imagefield_chem_mol_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sim",
            name="similarity_photo",
            field=models.CharField(default=0, max_length=200, verbose_name="结构"),
        ),
    ]
