# Generated by Django 4.1 on 2024-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0008_sim_similarity_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sim", options={"ordering": ["-similarity_data"]},
        ),
        migrations.AddField(
            model_name="sim",
            name="similarity_mol",
            field=models.CharField(default=0, max_length=200, verbose_name="分子式"),
        ),
    ]
