# Generated by Django 4.1 on 2025-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0009_alter_sim_options_sim_similarity_mol"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chem_mol",
            options={"verbose_name": "化学分子信息", "verbose_name_plural": "化学分子数据库"},
        ),
        migrations.AlterModelOptions(
            name="fil",
            options={"verbose_name": "文件上传库信息", "verbose_name_plural": "文件数据库"},
        ),
        migrations.AlterModelOptions(
            name="fun",
            options={"verbose_name": "网站功能信息", "verbose_name_plural": "网站功能链接数据库"},
        ),
        migrations.AlterModelOptions(
            name="test_chem_mol",
            options={"verbose_name": "待审核化学分子信息", "verbose_name_plural": "待审核化学分子数据库"},
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Chemical_Safety",
            field=models.CharField(default=0, max_length=200, verbose_name="化学品安全"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="IUPAC_Name",
            field=models.CharField(default=0, max_length=200, verbose_name="IUPAC名称"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Inchi",
            field=models.CharField(default=0, max_length=200, verbose_name="Inchi"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Molecular_Weight",
            field=models.CharField(default=0, max_length=200, verbose_name="分子量"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Synonyms",
            field=models.CharField(default=0, max_length=500, verbose_name="同义词"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Chemical_Safety",
            field=models.CharField(default=0, max_length=200, verbose_name="化学品安全"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="IUPAC_Name",
            field=models.CharField(default=0, max_length=200, verbose_name="IUPAC名称"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Inchi",
            field=models.CharField(default=0, max_length=200, verbose_name="Inchi"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Inchikey",
            field=models.CharField(default=0, max_length=200, verbose_name="Inchikey"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Molecular_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子式"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Molecular_Weight",
            field=models.CharField(default=0, max_length=200, verbose_name="分子量"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="SMILES",
            field=models.CharField(default=0, max_length=200, verbose_name="SMILES表示"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Synonyms",
            field=models.CharField(default=0, max_length=500, verbose_name="同义词"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="photo",
            field=models.CharField(default=0, max_length=200, verbose_name="结构"),
        ),
        migrations.AlterField(
            model_name="chem_mol",
            name="Inchikey",
            field=models.CharField(default=0, max_length=200, verbose_name="Inchikey"),
        ),
        migrations.AlterField(
            model_name="chem_mol",
            name="Molecular_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子式"),
        ),
        migrations.AlterField(
            model_name="test_chem_mol",
            name="CAS_Registry_Number_CAS",
            field=models.CharField(max_length=200, verbose_name="CAS"),
        ),
        migrations.AlterField(
            model_name="test_chem_mol",
            name="Density_dens",
            field=models.CharField(default=0, max_length=200, verbose_name="密度"),
        ),
        migrations.AlterField(
            model_name="test_chem_mol",
            name="Normal_boiling_temperature_Tb",
            field=models.CharField(default=0, max_length=200, verbose_name="常沸点温度"),
        ),
        migrations.AlterField(
            model_name="test_chem_mol",
            name="Normal_melting_temperature_Tm",
            field=models.CharField(default=0, max_length=200, verbose_name="正常熔化温度"),
        ),
    ]
