# Generated by Django 4.1 on 2025-02-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0010_alter_chem_mol_options_alter_fil_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chem_mol", old_name="Density_dens", new_name="Density",
        ),
        migrations.RenameField(
            model_name="test_chem_mol", old_name="Density_dens", new_name="Density",
        ),
        migrations.RemoveField(model_name="chem_mol", name="Inchi",),
        migrations.RemoveField(model_name="chem_mol", name="Inchikey",),
        migrations.RemoveField(model_name="test_chem_mol", name="Inchi",),
        migrations.RemoveField(model_name="test_chem_mol", name="Inchikey",),
        migrations.AddField(
            model_name="chem_mol",
            name="Animal_Drugs",
            field=models.CharField(default=0, max_length=200, verbose_name="动物药品"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Boiling_Point",
            field=models.CharField(default=0, max_length=200, verbose_name="沸点"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Chemical_Classes",
            field=models.CharField(default=0, max_length=200, verbose_name="化学类别"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Collision_Cross_Section",
            field=models.CharField(default=0, max_length=200, verbose_name="碰撞横截面"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Color",
            field=models.CharField(default=0, max_length=200, verbose_name="颜色"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Complexity",
            field=models.CharField(default=0, max_length=200, verbose_name="复杂性"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Compound_Is_Canonicalized",
            field=models.CharField(default=0, max_length=200, verbose_name="复合词被规范化"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Compound_Name",
            field=models.CharField(default=0, max_length=200, verbose_name="化合物名称"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Covalently_Bonded_Unit_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="共价键合单位计数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Database_Log",
            field=models.CharField(default=0, max_length=200, verbose_name="数据库日志"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Decomposition",
            field=models.CharField(default=0, max_length=200, verbose_name="分解"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Defined_Atom_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="定义的原子立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Defined_Bond_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="定义的键立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Description",
            field=models.CharField(default=0, max_length=200, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Dissociation_Constants",
            field=models.CharField(default=0, max_length=200, verbose_name="解离常数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Drugs",
            field=models.CharField(default=0, max_length=200, verbose_name="药物"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Exact_Mass",
            field=models.CharField(default=0, max_length=200, verbose_name="精确质量"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Flash_Point",
            field=models.CharField(default=0, max_length=200, verbose_name="闪点"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Form",
            field=models.CharField(default=0, max_length=200, verbose_name="形状"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Heavy_Atom_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="重原子计数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Human_Drugs",
            field=models.CharField(default=0, max_length=200, verbose_name="人用药物"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Hydrogen_Bond_Acceptor_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="氢键受体计数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Hydrogen_Bond_Donor_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="氢键供体计数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="IR_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="红外光谱"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Isotope_Atom_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="同位素原子数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Kovats_Retention_Index",
            field=models.CharField(
                default=0, max_length=200, verbose_name="Kovats_保留指数"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Mass_Spectrometry",
            field=models.CharField(default=0, max_length=200, verbose_name="质谱法"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Melting_Pointnt",
            field=models.CharField(default=0, max_length=200, verbose_name="熔点"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Molecular_Structure_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子结构式"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Monoisotopic_Mass",
            field=models.CharField(default=0, max_length=200, verbose_name="单同位素质量"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Odor",
            field=models.CharField(default=0, max_length=200, verbose_name="气味"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Other_Experimental_Properties",
            field=models.CharField(default=0, max_length=200, verbose_name="其他实验性质"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Other_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="其他光谱 "),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Physical_Description",
            field=models.CharField(default=0, max_length=200, verbose_name="物理描述"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="PubChem_CID",
            field=models.CharField(
                default=0, max_length=200, verbose_name="PubChem_CID"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Raman_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="拉曼光谱"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Related_Compounds",
            field=models.CharField(default=0, max_length=200, verbose_name="相关化合物"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Rotatable_Bond_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="可旋转的键数"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Shelf_Life",
            field=models.CharField(default=0, max_length=200, verbose_name="保质期"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Solubility",
            field=models.CharField(default=0, max_length=200, verbose_name="溶解度"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="SpringerMaterials_Properties",
            field=models.CharField(
                default=0, max_length=200, verbose_name="SpringerMaterials_属性"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Stability",
            field=models.CharField(default=0, max_length=200, verbose_name="稳定性"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Topological_Polar_Surface_Area",
            field=models.CharField(default=0, max_length=200, verbose_name="拓扑极表面积"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="UV_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="紫外光谱"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Undefined_Atom_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="未定义的原子立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Undefined_Bond_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="未定义的键立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="Vapor_Pressure",
            field=models.CharField(default=0, max_length=200, verbose_name="蒸气压"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="XLogP3",
            field=models.CharField(default=0, max_length=200, verbose_name="XLogP3"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="_1D_NMR_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="一维核磁共振波谱"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="_2D_NMR_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="2D_NMR_波谱"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Boiling_Point",
            field=models.CharField(default=0, max_length=200, verbose_name="沸点"),
        ),
        migrations.AddField(
            model_name="sim",
            name="CAS_Registry_Number_CAS",
            field=models.CharField(default=0, max_length=200, verbose_name="CAS"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Color",
            field=models.CharField(default=0, max_length=200, verbose_name="颜色"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Compound_Name",
            field=models.CharField(default=0, max_length=200, verbose_name="化合物名称"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Density",
            field=models.CharField(default=0, max_length=200, verbose_name="密度"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Description",
            field=models.CharField(default=0, max_length=200, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Electrical_conductivity_econd",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name="sim",
            name="Flash_Point",
            field=models.CharField(default=0, max_length=200, verbose_name="闪点"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Form",
            field=models.CharField(default=0, max_length=200, verbose_name="形状"),
        ),
        migrations.AddField(
            model_name="sim",
            name="IUPAC_Name",
            field=models.CharField(default=0, max_length=200, verbose_name="IUPAC名称"),
        ),
        migrations.AddField(
            model_name="sim",
            name="InchI",
            field=models.CharField(default=0, max_length=200, verbose_name="InchI"),
        ),
        migrations.AddField(
            model_name="sim",
            name="InchIkey",
            field=models.CharField(default=0, max_length=200, verbose_name="InchIkey"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Melting_Pointnt",
            field=models.CharField(default=0, max_length=200, verbose_name="熔点"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Molecular_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子式"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Molecular_Structure_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子结构式"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Molecular_Weight",
            field=models.CharField(default=0, max_length=200, verbose_name="分子量"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Odor",
            field=models.CharField(default=0, max_length=200, verbose_name="气味"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Physical_Description",
            field=models.CharField(default=0, max_length=200, verbose_name="物理描述"),
        ),
        migrations.AddField(
            model_name="sim",
            name="PubChem_CID",
            field=models.CharField(
                default=0, max_length=200, verbose_name="PubChem_CID"
            ),
        ),
        migrations.AddField(
            model_name="sim",
            name="Related_Compounds",
            field=models.CharField(default=0, max_length=200, verbose_name="相关化合物"),
        ),
        migrations.AddField(
            model_name="sim",
            name="SMILES",
            field=models.CharField(default=0, max_length=200, verbose_name="SMILES表示"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Solubility",
            field=models.CharField(default=0, max_length=200, verbose_name="溶解度"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Synonyms",
            field=models.CharField(default=0, max_length=500, verbose_name="同义词"),
        ),
        migrations.AddField(
            model_name="sim",
            name="Vapor_Pressure",
            field=models.CharField(default=0, max_length=200, verbose_name="蒸气压"),
        ),
        migrations.AddField(
            model_name="sim",
            name="photo",
            field=models.CharField(default=0, max_length=200, verbose_name="结构"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Animal_Drugs",
            field=models.CharField(default=0, max_length=200, verbose_name="动物药品"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Boiling_Point",
            field=models.CharField(default=0, max_length=200, verbose_name="沸点"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Chemical_Classes",
            field=models.CharField(default=0, max_length=200, verbose_name="化学类别"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Collision_Cross_Section",
            field=models.CharField(default=0, max_length=200, verbose_name="碰撞横截面"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Color",
            field=models.CharField(default=0, max_length=200, verbose_name="颜色"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Complexity",
            field=models.CharField(default=0, max_length=200, verbose_name="复杂性"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Compound_Is_Canonicalized",
            field=models.CharField(default=0, max_length=200, verbose_name="复合词被规范化"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Compound_Name",
            field=models.CharField(default=0, max_length=200, verbose_name="化合物名称"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Covalently_Bonded_Unit_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="共价键合单位计数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Database_Log",
            field=models.CharField(default=0, max_length=200, verbose_name="数据库日志"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Decomposition",
            field=models.CharField(default=0, max_length=200, verbose_name="分解"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Defined_Atom_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="定义的原子立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Defined_Bond_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="定义的键立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Description",
            field=models.CharField(default=0, max_length=200, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Dissociation_Constants",
            field=models.CharField(default=0, max_length=200, verbose_name="解离常数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Drugs",
            field=models.CharField(default=0, max_length=200, verbose_name="药物"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Exact_Mass",
            field=models.CharField(default=0, max_length=200, verbose_name="精确质量"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Flash_Point",
            field=models.CharField(default=0, max_length=200, verbose_name="闪点"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Form",
            field=models.CharField(default=0, max_length=200, verbose_name="形状"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Heavy_Atom_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="重原子计数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Human_Drugs",
            field=models.CharField(default=0, max_length=200, verbose_name="人用药物"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Hydrogen_Bond_Acceptor_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="氢键受体计数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Hydrogen_Bond_Donor_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="氢键供体计数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="IR_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="红外光谱"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Isotope_Atom_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="同位素原子数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Kovats_Retention_Index",
            field=models.CharField(
                default=0, max_length=200, verbose_name="Kovats_保留指数"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Mass_Spectrometry",
            field=models.CharField(default=0, max_length=200, verbose_name="质谱法"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Melting_Pointnt",
            field=models.CharField(default=0, max_length=200, verbose_name="熔点"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Molecular_Structure_Formla",
            field=models.CharField(default=0, max_length=200, verbose_name="分子结构式"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Monoisotopic_Mass",
            field=models.CharField(default=0, max_length=200, verbose_name="单同位素质量"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Odor",
            field=models.CharField(default=0, max_length=200, verbose_name="气味"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Other_Experimental_Properties",
            field=models.CharField(default=0, max_length=200, verbose_name="其他实验性质"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Other_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="其他光谱 "),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Physical_Description",
            field=models.CharField(default=0, max_length=200, verbose_name="物理描述"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="PubChem_CID",
            field=models.CharField(
                default=0, max_length=200, verbose_name="PubChem_CID"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Raman_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="拉曼光谱"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Related_Compounds",
            field=models.CharField(default=0, max_length=200, verbose_name="相关化合物"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Rotatable_Bond_Count",
            field=models.CharField(default=0, max_length=200, verbose_name="可旋转的键数"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Shelf_Life",
            field=models.CharField(default=0, max_length=200, verbose_name="保质期"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Solubility",
            field=models.CharField(default=0, max_length=200, verbose_name="溶解度"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="SpringerMaterials_Properties",
            field=models.CharField(
                default=0, max_length=200, verbose_name="SpringerMaterials_属性"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Stability",
            field=models.CharField(default=0, max_length=200, verbose_name="稳定性"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Topological_Polar_Surface_Area",
            field=models.CharField(default=0, max_length=200, verbose_name="拓扑极表面积"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="UV_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="紫外光谱"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Undefined_Atom_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="未定义的原子立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Undefined_Bond_Stereocenter_Count",
            field=models.CharField(
                default=0, max_length=200, verbose_name="未定义的键立体中心计数"
            ),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="Vapor_Pressure",
            field=models.CharField(default=0, max_length=200, verbose_name="蒸气压"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="XLogP3",
            field=models.CharField(default=0, max_length=200, verbose_name="XLogP3"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="_1D_NMR_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="一维核磁共振波谱"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="_2D_NMR_Spectra",
            field=models.CharField(default=0, max_length=200, verbose_name="2D_NMR_波谱"),
        ),
        migrations.AlterField(
            model_name="chem_mol",
            name="CAS_Registry_Number_CAS",
            field=models.CharField(default=0, max_length=200, verbose_name="CAS"),
        ),
        migrations.AlterField(
            model_name="test_chem_mol",
            name="CAS_Registry_Number_CAS",
            field=models.CharField(default=0, max_length=200, verbose_name="CAS"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="InchI",
            field=models.CharField(default=0, max_length=200, verbose_name="InchI"),
        ),
        migrations.AddField(
            model_name="chem_mol",
            name="InchIkey",
            field=models.CharField(default=0, max_length=200, verbose_name="InchIkey"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="InchI",
            field=models.CharField(default=0, max_length=200, verbose_name="InchI"),
        ),
        migrations.AddField(
            model_name="test_chem_mol",
            name="InchIkey",
            field=models.CharField(default=0, max_length=200, verbose_name="InchIkey"),
        ),
    ]
