# Generated by Django 4.1 on 2025-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chemai_data", "0011_rename_density_dens_chem_mol_density_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chem_mol",
            old_name="_1D_NMR_Spectra",
            new_name="te_1D_NMR_Spectra",
        ),
        migrations.RenameField(
            model_name="chem_mol",
            old_name="_2D_NMR_Spectra",
            new_name="te_2D_NMR_Spectra",
        ),
    ]
